### ISSUE TITLE
Splitting 'virtual terminal sequence' across multiple calls to WriteConsole

### ISSUE THREAD

**Issue by glenn-slayden** [MicrosoftDocs/Console-Docs#108]
I was trying to find out if the Windows 10 virtual terminal processing allows **ANSI** escape sequences to be arbitrarily split across multiple sequential calls to `WriteConsoleW`, and I couldn't seem to find the answer on this page.

Consider the control sequence `"\x1b[92m"`, which sets the foreground color to green. Since it is 5 characters long `{ '\x1b', '[', '9', '2', 'm' }`, there are 4 places it could be split in order to submit it with either 2, 3, 4, or 5 separate `WriteConsoleW` calls in various ways.

The following **C#** example investigates...

    [DllImport("kernel32.dll")]
    static extern IntPtr GetStdHandle(int device);

    [DllImport("kernel32.dll")]
    static extern bool GetConsoleMode(IntPtr h, out int mode);

    [DllImport("kernel32.dll")]
    static extern bool SetConsoleMode(IntPtr h, int mode);

    [DllImport("kernel32.dll", ExactSpelling = true)]
    static extern bool WriteConsoleW(
        IntPtr h, 
        [MarshalAs(UnmanagedType.LPWStr)] string s, 
        int cch,
        out int cch_out, 
        IntPtr _);

    static void Main()
    {
        var h = GetStdHandle(-11);
        GetConsoleMode(h, out int _mode);
        SetConsoleMode(h, _mode | 4);

        var esc = '\x1b';
        var msg = $"{esc}[92mHello,{esc}[0m world!";

        // write the first 3 chars, ending after the '9' inside the first ANSI sequence
        WriteConsoleW(h, msg, 3, out _, IntPtr.Zero);

        // write the next 9 chars, ending after just one char of the second ANSI sequence
        WriteConsoleW(h, msg.Substring(3), 9, out _, IntPtr.Zero);

        // write the remaining 3 characters of the second control sequence
        WriteConsoleW(h, msg.Substring(12), msg.Length - 12, out _, IntPtr.Zero);
    }

Turns out, the answer is 'yes,' ANSI control sequences appear to still be properly interpreted when split across multiple `WriteConsoleW` calls.

![hw](https://user-images.githubusercontent.com/5589855/65674326-3a58d480-e001-11e9-9e8d-303e62c78e88.png)

Apparently the console delays outputting any data that depends on the result of a partially-submitted escape sequence until additional characters which conclusively either complete or vacate the pending command are received. Feel free to use any of this information if you wish to add a note to the [docs page](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences). Perhaps as follows:

<h1>Suggested Edit</h1>

> (existing text...) **Simple Cursor Positioning** <br>In all of the following descriptions, ESC is always the hexadecimal value 0x1B. No spaces are to be included in terminal sequences. (new text...) **Individual terminal sequences can be split, at any character position, across multiple sequential calls to `WriteFile` or `WriteConsole`.** (existing text...) For an example of how these sequences are used in practice, please see the example at the end of this topic.

**Comment by KalleOlaviNiemitalo** [comment]
If there is a chance that more than one process (or thread) may be writing to the same console in parallel, I guess it is better to write the whole virtual terminal sequence in one API call.

**Comment by miniksa** [comment]
I believe that they *can* be split across calls just like anything in the console can. And we do our best to reassemble it appropriately on the other side.

But like @KalleOlaviNiemitalo says, it's probably better to just write the whole thing in one call because I can't stop parallel process issues on the console side no matter how hard I try.

**Comment by KalleOlaviNiemitalo** [comment]
Running this in cmd.exe in conhost of Windows 10 20H2:

```
powershell -Command "[Console]::Write([Char]27 + '[31')" && powershell -Command "[Console]::WriteLine('mhello' + [Char]27 + '[m')"
```

displays `mhello` in the default color. I guess cmd.exe disables the ENABLE_VIRTUAL_TERMINAL_PROCESSING mode before it runs the second `powershell` process, and the console host aborts the virtual terminal sequence at that point.

* <https://github.com/microsoft/terminal/blob/825039ea177b9f83a2ad05d3a8238df78b98055f/src/host/getset.cpp#L407-L413>
* <https://github.com/microsoft/terminal/blob/825039ea177b9f83a2ad05d3a8238df78b98055f/src/terminal/parser/stateMachine.cpp#L1988-L1999>

In Windows Terminal 1.3.2651.0 however, the same command displays `hello` in red. 🤔

**Comment by DHowett** [comment]
ConPTY defaults to VT_PROCESSING, so when cmd saves/restores the mode between commands it ends up leaving it turned on. This is like setting VirtualTerminalLevel (DWORD) = 1. :smile:
