### ISSUE TITLE
The same paragraph - twice.

### ISSUE THREAD

**Issue by Ash72** [MicrosoftDocs/Console-Docs#114]
The next paragraph is repeated twice:
With exception of the leading byte and trailing byte flags, the remaining flags describing line drawing and reverse video (swap foreground and background colors) can be useful for other languages to emphasize portions of output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ea4fba-5919-fff6-9941-f213a557c651
* Version Independent ID: 5c22080b-6969-4721-5e5c-40c348680701
* Content: [SetConsoleMode function - Windows Console](https://docs.microsoft.com/en-us/windows/console/setconsolemode#feedback)
* Content Source: [docs/setconsolemode.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/setconsolemode.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
OK. If you send a PR, I can merge it quick. Otherwise, I'll get this in the next docs pass.
