### ISSUE TITLE
Update OSC section on "Console Virtual Terminal Sequences" to include updated string terminators

### ISSUE THREAD

**Issue by zadjii-msft** [MicrosoftDocs/Console-Docs#120]
> In ColorTool I see we use BEL as OSC end. I believe it aligns with xterm.
> `string s = $"\x1b]4;{vtIndex};rgb:{color.R:X}/{color.G:X}/{color.B:X}\x7"` 
> https://github.com/microsoft/terminal/blob/master/src/tools/ColorTool/ColorTool/ConsoleTargets/VirtualTerminalConsoleTarget.cs
> but in the doc, it says ESC as end
> I think it wants to say "ESC \", which is ST

We should make sure specifically the string terminators for the OSC section get updated.

(subset of #91)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#window-title)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by gh28** [comment]
Typo:

> I think it wants to say "ESC \\", which is ST

**Comment by miniksa** [comment]
This could be cross-referenced by anyone against the code in the Microsoft/Terminal repo.

**Comment by KalleOlaviNiemitalo** [comment]
This supports either BEL or ST as the terminator after OSC: <https://github.com/microsoft/terminal/blob/38ebf48d79f65d6460451e1b4ff5c5f6f010d9b9/src/terminal/parser/stateMachine.cpp#L261-L271>

However, it seems to recognize only U+009C as STRING TERMINATOR (ST), not ESC 0x5C. Unless ESC 0x5C is mapped to U+009C by some other function, this may be a violation of ECMA-48.
