### ISSUE TITLE
Inconsistent SAL annotation for lpNumberOfCharsWritten

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/Console-Docs#121]
This documentation page contains an `_Out_` annotation on the `lpNumberOfCharsWritten` parameter. That doesn't match the annotation in the Windows SDK header *ConsoleAPI.h* (versions 17134, 17763, 18362). The SDK header has an `_Out_opt_` annotation.

I would have expected the documentation to agree with the annotation in the header file. Is this a documentation bug, or is the documentation accurate, with the implementation opting to weaken the pre-conditions?

Please update the documentation in case this turns out to be a documentation bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5217790-3d20-b461-f625-955cc24c60ad
* Version Independent ID: 5fddd692-19bb-414b-a83c-f46978575b1f
* Content: [WriteConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/writeconsole)
* Content Source: [docs/writeconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/writeconsole.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
I checked the code behind the header. It's legitimately opt. This is a doc bug. Fixing.
