### ISSUE TITLE
The function does not work in Windows 10 (1909).

### ISSUE THREAD

**Issue by OpenGreatDream** [MicrosoftDocs/Console-Docs#123]
This is my sample code in C:
BOOL result = SetConsoleCtrlHandler(NULL, TRUE);

And the same function code in C#:
Console.TreatControlCAsInput = true;

After I called the function, pressing Ctrl + C would still cause the console to close.

Please help me out!

**Comment by DHowett-MSFT** [comment]
You'll need to provide a little more info than that. Are you using another terminal application? If so, what does it say? Are you using another shell, like powershell, that might be intercepting <kbd>Ctrl+C</kbd>?

**Comment by OpenGreatDream** [comment]
I used the original conhost.exe as the terminal.

**Comment by OpenGreatDream** [comment]
> You'll need to provide a little more info than that. Are you using another terminal application? If so, what does it say? Are you using another shell, like powershell, that might be intercepting Ctrl+C?

I used the original conhost.exe as the terminal.

**Comment by miniksa** [comment]
This isn't a docs issue as far as I can tell. Resolving. For further assistance with code issues, please see the `Microsoft/Terminal` repository or use the Feedback Hub. Thanks!
