### ISSUE TITLE
Difficult to tell that Cursor Visibility "disable" options end in L instead of pipe

### ISSUE THREAD

**Issue by JohnMcPMS** [MicrosoftDocs/Console-Docs#133]
On docs.microsoft.com, the font in use makes it difficult to tell that the Cursor Visibility sequences that disable blink/show end in a lowercase L rather than a pipe (|).  Only after searching elsewhere did I discover the difference on stackoverflow, where the example was using a serif'd "code" font.

I'm not sure if its possible, but it might be worth displaying all of the Sequence column values in a code block, or whatever fixed with serif'd font is available (I suppose you could even use Cascadia Code ;) ).

**Comment by miniksa** [comment]
Full update of that doc should happen at some point including reformatting all the sequences in a code block or something, but I've added a brief tip there to clarify.
