### ISSUE TITLE
Download PDF button is missing on this page

### ISSUE THREAD

**Issue by sinand99** [MicrosoftDocs/Console-Docs#139]
Please add Download PDF link here so we can download for offline reading.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0101f688-e282-e697-831e-4c41e1ac0ce7
* Version Independent ID: 46961212-91d1-3b95-9d26-81788db9af23
* Content: [Console Functions - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-functions)
* Content Source: [docs/console-functions.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-functions.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by ysc3839** [comment]
A workaround is using [docfx](https://dotnet.github.io/docfx/) to build this document.

**Comment by miniksa** [comment]
I don't know how to solve this as it's a function of the build system, I think. @mattwojo, do you have any ideas?

**Comment by mattwojo** [comment]
I know how to do this... but we need to figure out who the designated administrator is for this repo. I'll follow up in chat.

**Comment by mattwojo** [comment]
Ok, looks like this is working now. Thanks for raising the issue @sinand99!
Resolution commit: https://github.com/MicrosoftDocs/Console-Docs/commit/9177034673d839ac43945f66e0166c3556457091
