### ISSUE TITLE
Document Cursor Shape Escape Sequences

### ISSUE THREAD

**Issue by rksouthee** [MicrosoftDocs/Console-Docs#140]
Windows Console has support for using Virtual Terminal Sequences to change the cursor shape. I've used the following sequences and they all seem to work.

* `ESC [ 0 SP q` blinking block
* `ESC [ 1 SP q` blinking block
* `ESC [ 2 SP q` steady block
* `ESC [ 3 SP q` blinking underline
* `ESC [ 4 SP q` steady underline
* `ESC [ 5 SP q` blinking bar
* `ESC [ 6 SP q` steady bar

Where SP is a literal space character.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/pull/7379> changed `ESC [ 0 SP q` to mean the default cursor shape configured by the user. <https://github.com/microsoft/terminal/issues/1604#issuecomment-708648546> says that change is in a Windows Insider build, so it is not specific to Windows Terminal.

**Comment by pizzaz93** [comment]
I've filled in the parts of the chart I can populate based on the report in this issue.
I'm not sure if <n> or ? are the equivalent of SP?
