### ISSUE TITLE
Bug in Create PseudoConsole Session Sample Code 

### ISSUE THREAD

**Issue by hyperlogic** [MicrosoftDocs/Console-Docs#141]
The following code in snippet on [Creating The Hosted Process](https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session#creating-the-hosted-process) contains a memory corruption bug.

    // Create mutable text string for CreateProcessW command line string.
    const size_t bytesRequired = wcslen(childApplication) + 1; // +1 null terminator
    PWSTR cmdLineMutable = (PWSTR)HeapAlloc(GetProcessHeap(), 0, bytesRequired);

    if (!cmdLineMutable)
    {
        return E_OUTOFMEMORY;
    }

    wcscpy_s(cmdLineMutable, bytesRequired, childApplication);

This snippet does not allocate enough memory for the cmdLineMutable wide string. This can lead to memory corruption during the later wsccpy_s() call.

Here's a suggested fix:

    // Create mutable text string for CreateProcessW command line string.
    const size_t wcharsRequired = wcslen(childApplication) + 1; // +1 null terminator
    PWSTR cmdLineMutable = (PWSTR)HeapAlloc(GetProcessHeap(), 0, sizeof(wchar_t) * wcharsRequired);

    if (!cmdLineMutable)
    {
        return E_OUTOFMEMORY;
    }

    wcscpy_s(cmdLineMutable, wcharsRequired, childApplication);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ed724a-32d9-72fc-a938-e181e3fde0e8
* Version Independent ID: d6706818-fb3d-7400-a549-9d3a77602f33
* Content: [Creating a Pseudoconsole session - Windows Console](https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session)
* Content Source: [docs/creating-a-pseudoconsole-session.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/creating-a-pseudoconsole-session.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Oh shoot. You're absolutely right. That is the right change. Thank you.
