### ISSUE TITLE
Add disclaimers to APIs that will behave differently in conpty mode

### ISSUE THREAD

**Issue by zadjii-msft** [MicrosoftDocs/Console-Docs#147]
Case in point, `GetConsoleWindow`. We should add a note that this returns a dummy value in conpty mode. We should additionally note that if developers want to make sure their apps work on the broadest category of terminal applications, they should avoid using it. 

See also microsoft/terminal#6887

**Comment by miniksa** [comment]
The avoid using it one, I think I got done with #162 given it has a banner on top about not recommending it and a banner on the bottom explaining that it can't/won't work with VT.

I'll also add a remark that it returns a dummy value with the conpty mode and I think this is settled.
