### ISSUE TITLE
Determine which pages would benefit from human translation

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/Console-Docs#152]
Est. 10-15 max for budget reasons, use `ms.localizationpriority: high`.

You might also update the `ms.topic` values at the same time to something more relevant than the `article` that currently is assigned to all of those. See https://review.docs.microsoft.com/en-us/help/contribute/metadata-attributes?branch=master#mstopic-quick-reference for valid values.

**Comment by pizzaz93** [comment]
@miniksa If I understood this correctly it would be evaluating all the files under `docs` and `includes` as one of the following classifications:
article, conceptual, contributor-guide, interactive-tutorial, overview, quickstart, reference, sample or tutorial. (https://docs.microsoft.com/en-us/contribute/metadata#required-metadata)

The other item would be evaluating these articles and identifying 10-15 high priority ones to add a metadata classification that prioritizes their translation.

**Comment by mattwojo** [comment]
Unfortunately there is no longer a team that supports this, so closing this issue.
