### ISSUE TITLE
Legacy mode layout settings broken

### ISSUE THREAD

**Issue by vvascanus** [MicrosoftDocs/Console-Docs#156]
I check "use legacy console". I require the console window size (and buffer size) to stay fixed at a size I set,  normally **width 80** and **height 42**.  I **uncheck** "let system position window". When I load a text file into a new console window, the console opens with the specified size. As soon as I drag the window to another position, the size changes, typically the width shrinks to 78 columns and height anywhere from 32 to 40. This has been consistenly happening with the new version of the console.   (Font is set to Lucida Console 24).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a3244ed-e1a9-4e16-0a60-246f679c9afe
* Version Independent ID: 6715591d-2458-9008-edbe-eaed47051f72
* Content: [Legacy Console Mode – Windows Desktop - Windows Console](https://docs.microsoft.com/en-us/windows/console/legacymode)
* Content Source: [docs/legacymode.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/legacymode.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by DHowett** [comment]
Since you cannot just “load a text file” into the console, you must be using some additional software. Would you mind sharing what that is? It is difficult to troubleshoot when we have to guess.

**Comment by miniksa** [comment]
Closing stale issue.
