### ISSUE TITLE
CONSOLE_READCONSOLE_CONTROL::dwCtrlWakeupMask is a bit mask, not a character

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/Console-Docs#158]
**dwCtrlWakeupMask** is documented to be a control character but it instead seems to be a bit mask in which each bit corresponds to one of the 32 control characters 0x00 to 0x1F.

> ```C
>   ULONG dwCtrlWakeupMask;
> ```

> **dwCtrlWakeupMask**  
> A user-defined control character used to signal that the read is complete.

https://github.com/microsoft/terminal/blob/6c869ebb269155194e668b768d3424eb2a22a125/src/host/readDataCooked.cpp#L495

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ea95a4-7dad-cc82-7f3d-3bbc9a75fb33
* Version Independent ID: 4e8ad957-9707-9f59-1a42-e926dcd699b0
* Content: [CONSOLE_READCONSOLE_CONTROL structure - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-readconsole-control)
* Content Source: [docs/console-readconsole-control.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-readconsole-control.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Well how about that. You're absolutely right. Fixing.
