### ISSUE TITLE
Add remark about the new Terminal app not supporting this function

### ISSUE THREAD

**Issue by aziascreations** [MicrosoftDocs/Console-Docs#159]
I think a remark about the fact that the new Terminal app doesn't and won't support any font related functions should be added somewhere in the documentation.

I recently tried using this function with no success, even tho it should have worked according to the documentation.
I then made an issue on the project's repo (https://github.com/microsoft/terminal/issues/7585)
And I was told that it won't be supported by design (https://github.com/microsoft/terminal/issues/6832#issuecomment-655684556)

Adding just a little line in the remarks section about this would help a lot in these types of issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f6670e-2349-22a4-d8f1-9bba9f187a07
* Version Independent ID: e368ad27-092b-6ef0-c7f6-c82ac7b0ec49
* Content: [SetCurrentConsoleFontEx function - Windows Console](https://docs.microsoft.com/en-us/windows/console/setcurrentconsolefontex)
* Content Source: [docs/setcurrentconsolefontex.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/setcurrentconsolefontex.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
That's a great call and I'll try to find time in the next pass of console docs to call out how the original console and Terminal are and will be different.

**Comment by miniksa** [comment]
I think #162 covers this.

I've added:
- A banner at the top saying that this API is generally not recommended
    - This banner links to a page talking about classic console APIs vs VT and why we're favoring VT
    - It also links to a roadmap talking about where the console came from and where we're going toward with the Terminal
- A banner in the remarks section that describes why this API is not recommended as it has no Virtual Terminal equivalent which makes it nigh impossible to remote properly and mesh with the other platforms and ecosystems where terminals are the norm.

If you don't think that's sufficient, please let me know with a further comment. The doc content should go live today/tomorrow and is visible in our main branch right now.
