### ISSUE TITLE
Says "PINPUT_RECORD" instead of "INPUT_RECORD"

### ISSUE THREAD

**Issue by kres0345** [MicrosoftDocs/Console-Docs#160]
Says "PINPUT_RECORD" instead of "INPUT_RECORD"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf2ea95-c942-16a0-9501-ba56be8c5c44
* Version Independent ID: 169d5761-f559-4b3f-ee7a-06befb96e1f2
* Content: [ReadConsoleInput function - Windows Console](https://docs.microsoft.com/en-us/windows/console/readconsoleinput)
* Content Source: [docs/readconsoleinput.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/readconsoleinput.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by DHowett** [comment]
Yes. In the Win32 API, all pointer types are prefixed with `P`. `PINPUT_BUFFER` is the same as `INPUT_BUFFER*`.

**Comment by kres0345** [comment]
ohh, okay. Felt a little too obvious to be a mistake
