### ISSUE TITLE
ClosePseudoConsole talks about an undeclared hOutput identifier

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/Console-Docs#170]
The remarks section talks of a `hOutput` identifier without defining it anywhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b02229f7-af1d-32c8-7877-c5afafabbff8
* Version Independent ID: 83b9fd10-3f5d-1391-2c90-9e32de3729b8
* Content: [ClosePseudoConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/closepseudoconsole)
* Content Source: [docs/closepseudoconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/closepseudoconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by DHowett** [comment]
Fair. We should link that to the CreatePseudoConsole docs, which documents `hOutput`.
