### ISSUE TITLE
Summary about WriteConsoleInput uses wrong access right

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/Console-Docs#171]
The summary incorrectly states that the `GENERIC_READ` access right is required. The correct one is the `GENERIC_WRITE` access right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ed1408-fab8-5417-680f-5cd5779c911c
* Version Independent ID: 0b4c4aa3-12c6-1d96-ec99-bb59565e0fc2
* Content: [Low-Level Console Input Functions - Windows Console](https://docs.microsoft.com/en-us/windows/console/low-level-console-input-functions)
* Content Source: [docs/low-level-console-input-functions.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/low-level-console-input-functions.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by henke37** [comment]
This also applies to the FlushConsoleInputBuffer function summary on the same page.

**Comment by miniksa** [comment]
Good catch, thank you.
