### ISSUE TITLE
sample code has error

### ISSUE THREAD

**Issue by tole2k** [MicrosoftDocs/Console-Docs#172]
error C2664: 'void ErrorExit(LPSTR)': cannot convert argument 1 from 'const char [13]' to 'LPSTR'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c07562d-f17f-a601-1518-32221c4255ba
* Version Independent ID: 1c26f9ac-3226-6e22-ee34-7a781c96d3ab
* Content: [Reading Input Buffer Events - Windows Console](https://docs.microsoft.com/en-us/windows/console/reading-input-buffer-events)
* Content Source: [docs/reading-input-buffer-events.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/reading-input-buffer-events.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
I just built this sample with Visual Studio 2019 in x64 configuration and it's fine.

I'm not sure what's going on with your configuration, but a plain old string literal `"Foo"` is definitely generally convertible to `char*` which is what `LPSTR` is a typedef for in `windows.h` and friends.
