### ISSUE TITLE
Open Windows Terminal Here

### ISSUE THREAD

**Issue by OfirGan** [MicrosoftDocs/Console-Docs#176]
Hope it is possible,

Add "Open Windows Terminal Here" to windows right click context manu, and start the terminal in the current right click location.

Thanks 😊

**Comment by zadjii-msft** [comment]
1. This is the _console_ docs repo, for the vintage in-box console. The Terminal docs are over at https://github.com/MicrosoftDocs/terminal, and Terminal feature requests should be made over at https://github.com/MicrosoftDocs/terminal.
2. This is something the Terminal already supports, see https://github.com/microsoft/terminal/issues/1060 and its PR https://github.com/microsoft/terminal/pull/6100, and also see the [list of open issues for the context menu entry](https://github.com/microsoft/terminal/issues?q=is%3Aopen+is%3Aissue+label%3AArea-ShellExtension)
