### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by WKleinschmit** [MicrosoftDocs/Console-Docs#180]
[Enter feedback here]

The created pseudoconsole session will attempt to inherit the cursor position of the paernt console.
should be
The created pseudoconsole session will attempt to inherit the cursor position of the parent console.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600cb1d1-7698-f4e8-2775-b1b7acc2c0f0
* Version Independent ID: 15c3bf4f-0aa1-9ecc-1288-a225cf13958f
* Content: [CreatePseudoConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(CONSOLEAPI%252FCreatePseudoConsole);k(CreatePseudoConsole);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.0);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.0);k(DevLang-C%252B%252B);k(TargetOS-Windows);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.0)%26rd%3Dtrue)
* Content Source: [docs/createpseudoconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/createpseudoconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Woops. Good call.

**Comment by miniksa** [comment]
Fixed in https://github.com/MicrosoftDocs/Console-Docs/commit/d0f7698ce8443ecb7a4b3c194a6b8dc2682063de
