### ISSUE TITLE
Virtual Terminal is regression

### ISSUE THREAD

**Issue by noman9607** [MicrosoftDocs/Console-Docs#183]
[Enter feedback here]
Why don't you guys from the Redmond campus visit the linux estate and see how great life is there? Can't find it?  Do you really think microsoft got where it is by being so inferior to linux? Nothing wrong with compatibility but you need a different approach here. You are wrong about almost everything and I suspect that you, like the blues brothers, have a bad attitude as well. I suggest lifting the low rather than lowering the high. Einstein said make things as simple as possible, but not simpler. Holding linux as the ideal to be copied is simple minded. By the way, I feel the correct term is console window, not terminal, for Windows and for God's sake there is no DOS box in Windows, it is a console window that emulates the dead, extinct, defunct days of the character generator chip.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ada9ec05-3269-9fb2-bd0b-b01bfafd86a7
* Version Independent ID: 3a38151f-1a94-fc14-29a1-d2b16bce6926
* Content: [Console documentation - Windows Console](https://docs.microsoft.com/en-us/windows/console/)
* Content Source: [docs/index.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/index.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by DHowett** [comment]
If you’re just going to be rude to us, go away.
