### ISSUE TITLE
Page "Console Process Groups" cannot be found via tree menu

### ISSUE THREAD

**Issue by j0le** [MicrosoftDocs/Console-Docs#193]
The Page "Console Process Groups" cannot be found via the tree menu on the left side.
By default the current page has an entry in the tree view and the tree view is expanded to show this entry.
But there is no entry for this page. So far I have only seen this with archived and/or outdated pages on docs.microsoft.com. 
I found this page with my search engine. 

Futhermore this page has a bad "path". There is only `Docs` at the top of the page and not something link `Docs / About Consoles / Console Process Groups`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6e01447-e1fa-bff4-707b-31d89048fce3
* Version Independent ID: 85e58a53-0d7b-1d76-709a-7902132db512
* Content: [Console Process Groups - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-process-groups)
* Content Source: [docs/console-process-groups.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-process-groups.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Oops. Looks like we missed putting a page into the table of contents doc. I'll get on that. It should fix both issues.

Thanks for the report!

**Comment by j0le** [comment]
Thank you :)
