### ISSUE TITLE
Example to show how to read cursor position

### ISSUE THREAD

**Issue by pr0g** [MicrosoftDocs/Console-Docs#196]
Hi there!

This ([console virtual terminal sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)) is a super helpful page and I've mostly been able to understand how to use the terminal sequences but one thing that's missing which I've been struggling to figure out how to do is read-back the cursor position.

In the [Query State](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#query-state) section of the document it states that `ESC [ 6 n` will report the cursor position in the form `ESC [ <r> ; <c> R` which is great, but I don't see how to parse that state back into a variable in the program. I'd ideally like to do something like this...

```c++
int r = 0;
int c = 0;
printf(CSI "6n");
scanf(CSI "%d;%dR", &r, &c);
```

When I try this I see the values of the current cursor position printed to the screen and then `scanf` just waits for input from the terminal as it needs a new-line to continue. I just want to swallow the output (not see it printed) and get the row/col position.

I'm sure there's a way to do this but I wasn't sure if it requires using [`ReadConsoleInput`](https://docs.microsoft.com/en-us/windows/console/readconsoleinput) or if it's possible to use native C functions like `scanf`?

If an example of how to do this could be presented in the article it would be incredibly helpful! 🙂

Thanks very much for your time,

Tom

(P.S. This is incredibly minor but in one of the code snippets the variable `dwRequestedInModes` is unused so can either be deleted or used in-place of `ENABLE_VIRTUAL_TERMINAL_INPUT` later on).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Hi @pr0g,

I'm glad it's been useful to you.

I will attempt to update the documentation in my next pass to include this information (and fix the little code snippet issue you graciously caught for us), but in the interim... let me see if I can help clear this up for you here.

You're on the right track with using `scanf`, `ReadConsole`, or `ReadConsoleInput` to get the position information back out and the pattern. I think you're just getting tripped up on the "cooked read" functionality of the input channel.

By default, the console typically prepares its own input line that it only sends through to the listening `STDIN` handle when the enter key is pressed. This can be seen on the `ENABLE_LINE_INPUT` flag on the input handle on the [SetConsoleMode](https://docs.microsoft.com/windows/console/setconsolemode) page. You may also be seeing it appear back on the screen because of the `ENABLE_ECHO_INPUT` flag.

I highly recommend that you disable those sorts of input modes when using the `ENABLE_VIRTUAL_TERMINAL_INPUT` flag and see if you start getting the raw byte by byte input and responses to your queries on the input handle through whichever read API you choose to use.

If that still doesn't work, let me know and I will happily investigate with you more deeply or pull in people who have worked in this area more recently than myself to help figure it out. This is just an off-the-top-of-my-head answer that will *probably* get you moving.

Thanks for your report!

**Comment by miniksa** [comment]
No problem! My typical recommended strategy with the flags is to do `GetConsoleMode`, do all the `|=` and `&= ~` to your heart's content, then `SetConsoleMode` it back. So it sounds like you're on the right track.

I typically use `WI_SetFlag` and `WI_ClearFlag` though so I don't make accidental bitwise flagging mistakes. If you haven't seen/heard of https://github.com/microsoft/wil, it contains those useful macros and plenty more wrappers, macros, and resource managers to make working with Win32 easier. We use them inside Windows all the time!

Let me know how it goes and good luck!

**Comment by pr0g** [comment]
Hi @miniksa!

Sorry for the slight delay in getting back to you, I just gave that a try and it worked like a charm! 😄 🎉 

I wasn't aware of [WIL](https://github.com/microsoft/wil) before but it looks great. It was easy to add to my project (I used the brilliant CMake `FetchContent` to bring it in 🙂 You can see the change [here](https://github.com/pr0g/hierarchy/commit/f75bf293b1b0ef5eb45f031cd6731e14e3a5e4ec)).

I'm afraid this is a slight tangent but I was wondering if you knew.  Is there any advice on how to reduce terminal flicker when doing an update? I have a super simple update loop in `main-win.cpp` ([line 87](https://github.com/pr0g/hierarchy/blob/main/main-win.cpp#L87)). I set the cursor position to be the top left of the window and clear the screen every update (each time the user presses a key) but when using the new [Windows Terminal](https://github.com/microsoft/terminal) I do get quite a bit of flicker as the number of elements on screen increases. Is there a trick to avoid this or something I can do to improve the quality?

Thanks again for your time and helpful suggestions!

Cheers,

Tom

**Comment by miniksa** [comment]
Hi Tom,

I'm glad it worked out for you. Wonderful! I do promise I will add some of these notes to the official documentation on my next pass.

For your other point... generally speaking... in lieu of clearing everything first before repainting... you would only paint the differences from the previous frame if possible. That might require you to track more data about what you've already displayed, but it will also significantly reduce the on-wire size of what you're communicating especially should someone use your utility over SSH or the like. Some of the best tools like `emacs` give the minimal VT required to do a graphical change from the previous display with lots of creativity. I'm not personally that familiar with `curses` (other than knowing it exists and approximately what it's used for) or if there's a suitable Windows port of it, but it might provide some amount of that built in.

If you're going to repaint absolutely every cell though, you might also consider just writing without clearing first and it may reduce the perceived flicker as the displayed frame cannot be snapped at a point where there's no content to display (and therefore quickly flash an empty page causing "flicker"). You could get tearing... but that might be less visually noticeable and more acceptable. I'm not aware of a sequence that is like "batch all these following commands and only release them when I say so". One might exist... and we might not have it implemented.

The Terminal and the conhost/ConPTY powering it do quite a bit of work to minimize the updates to the screen to reduce flickering. But a "full screen clear" command is almost... explicitly asking us for a flicker as we must invalidate EVERYTHING when that comes through.

Thanks,
--Michael

**Comment by pr0g** [comment]
Hi Michael,

Haha no rush at all, much appreciated! I have to say having actual code snippets is always a massive help! 🙂

Thank you very much for your detailed reply to my other question. I was afraid you were going to say that more or less 😛 I was hoping there was a special flag I might be able to turn on to magically fix it 😁

The good news is in my simple prototype I can pretty easily figure out the rows that need to be redrawn when something changes so can likely update the relevant rows based on that information. I'm actually using `ncurses` for the `macOS` version of my little demo but I don't believe there's an equivalent Windows port (yet?).

Thank you again for your help and thoughtful responses,

Cheers!


Tom
