### ISSUE TITLE
FreeConsole

### ISSUE THREAD

**Issue by devkadirselcuk** [MicrosoftDocs/Console-Docs#202]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b013865-fcaf-8009-6c6f-cf358d98914e
* Version Independent ID: 33211ae1-fe61-845c-040c-b92ea8b0e25f
* Content: [FreeConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/freeconsole)
* Content Source: [docs/freeconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/freeconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by zadjii-msft** [comment]
You gotta actually provide some info for us to be able to do something.
