### ISSUE TITLE
Windows Terminal cannot type

### ISSUE THREAD

**Issue by amm834** [MicrosoftDocs/Console-Docs#205]
When I upgraded to window 11,
my window terminal not working.

**Procedure**
```bash
Right Click > Open in windows terminals 
```
( I can search via `terminal` and choose the window terminals )
It opened PowerShell.
But cannot type in it.

I can use `cmd` or `powershell` but I want to use them in window terminals.
How can I fix it.
I try with others option like enabling the touch input service.
It didn't work.
How can I solve it.

**Comment by amm834** [comment]
Restarted the OS and it work again.

**Comment by anneheien197450-coder** [comment]
> When I upgraded to window 11, my window terminal not working.
> 
> **Procedure**
> 
> Right Click > Open in windows terminals 
> ( I can search via `terminal` and choose the window terminals ) It opened PowerShell. But cannot type in it.
> 
> I can use `cmd` or `powershell` but I want to use them in window terminals. How can I fix it. I try with others option like enabling the touch input service. It didn't work. How can I solve it.



> When I upgraded to window 11, my window terminal not working.
> 
> **Procedure**
> 
> Right Click > Open in windows terminals 
> ( I can search via `terminal` and choose the window terminals ) It opened PowerShell. But cannot type in it.
> 
> I can use `cmd` or `powershell` but I want to use them in window terminals. How can I fix it. I try with others option like enabling the touch input service. It didn't work. How can I solve it.

**Comment by anneheien197450-coder** [comment]
> Restarted the OS and it work again.
