### ISSUE TITLE
Error in documentation of OSC]4

### ISSUE THREAD

**Issue by vefatica** [MicrosoftDocs/Console-Docs#219]
It now says

`ESC ] 4 ; <i> ; rgb : <r> / <g> / <b> ESC`

It should say

`ESC ] 4 ; <i> ; rgb : <r> / <g> / <b> ESC \`

That is, the terminator for OSC]4 is ESC followed by a backslash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by vefatica** [comment]
There's also ST = 0x9c which works with WriteConsoleW (and not with WriteConsoleA) and which doesn't appear in the docs (I don't remember if it used to).

And I'm curious ... what happens internally when WriteConsoleW or WriteConsoleA is used ... is there a conversion ... which way does it go?

**Comment by DHowett** [comment]
The console uses UTF-16 internally, so all `-A` APIs are translated into their `-W` counterparts as soon as we get the data.

To your point, though, yes. ST is _actually_ `0x9C`; it is even specified in Unicode as such¹!. In an 8-bit-clean datastream, such as that provided by `WriteConsoleW`, you can stills submit 0x9C as ST². `WriteConsoleA` is, unfortunately, _not_ an 8-bit-clean datastream as it is subject to codepage translation³. To write an 8-bit `ST` using `WriteConsoleA`, you'll need to be aware of the current console codepage. As an example: if you're using codepage `65001` (UTF-8) you'll need to write `0xC2 0x9C` as that is how you encode `U+009C` in UTF-8.

¹ [`U+009C STRING TERMINATOR`](https://www.fileformat.info/info/unicode/char/009c/index.htm)
² The representation of `ST` in a 7-bit datastream is `0x1B 0x5C`, or `ESC \`! xterm defines the 8-bit control characters to be equivalent to their matching 7-bit control characters.
³ _Most_ codepages today keep ASCII in the lower half of the 256-position character table and use the upper half for extended characters. `0x9C` is of course in the upper half.
