### ISSUE TITLE
Screen Colors section appears to show incorrect escape sequence

### ISSUE THREAD

**Issue by lviolette** [MicrosoftDocs/Console-Docs#220]
[Enter feedback here]
In the Screen Colors section.  It shows the sequence to Modify Screen Colors with what I believe is an incorrect escape sequence.
It shows ESC]4...
It should be ESC[4...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by lviolette** [comment]
I was mistaken.  Ignore me please.

**Comment by miniksa** [comment]
It's alright. No problem. Thanks anyway!
