### ISSUE TITLE
Describe "intermediate read feature"

### ISSUE THREAD

**Issue by vaintroub** [MicrosoftDocs/Console-Docs#224]
[Enter feedback here]
The page says : Windows Server 2003 and Windows XP/2000: The intermediate read feature is not supported.
There is no explanation of the intermediate read. I gather something did not work in the past, and does now. What it is exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79e5945d-500f-6e07-c9db-4e71c6f3bb4e
* Version Independent ID: 19f1260a-b4e1-6773-a94a-110992784aa3
* Content: [ReadConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/readconsole)
* Content Source: [docs/readconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/readconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
I took a look at the code this morning to get you an answer.

If you have `ENABLE_LINE_INPUT` set with `SetConsoleMode` on the console input handle, then you're in cooked mode. In cooked mode, the console host will provide an edit line on your command-line application's behalf and calls to `ReadFile` or `ReadConsole` will not return until the enter key is pressed.

The `intermediate read` is an augmentation to that behavior on the `ReadConsole` call in cooked read mode. If you set a flag in `dwCtrlWakeupMask` on the `CONSOLE_READCONSOLE_CONTROL` structure and give it into `pinputControl` as you call `ReadConsole`, then the read will not necessarily wait for a newline, but will return on whichever character you specified as well. Does that make sense? If not, I can continue to try to clarify.

Additionally, the code inside the console host that services this call can be seen here, if that helps you investigate/understand it further: https://github.com/microsoft/terminal/blob/37e8769b3706402706d62f19202554080796b3e3/src/host/readDataCooked.cpp#L478-L503

I will formalize this into a doc content update at a future date. Thanks!

**Comment by vaintroub** [comment]
Ok, I see, thanks, this was a great answer. I understand it right, this would be the place to add own tab completion, if one were so inclined. Thanks for the code reference, did not expect that :)
