### ISSUE TITLE
Update documentation on "intermediate read feature" per #224

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/Console-Docs#225]
Someone asked and I answered. This represents putting the #224 discussion into the official documentation.

**Comment by pizzaz93** [comment]
**Cooked Mode** is when `ENABLE_LINE_INPUT` is set with `SetConsoleMode` on the console input handle. In cooked mode, the console host will provide an edit line on the command-line application's behalf and calls to `ReadFile` or `ReadConsole` will not return until the enter key is pressed.

**Intermediate Read** is an augmentation to that behavior on the `ReadConsole` call in cooked read mode. Setting a flag in `dwCtrlWakeupMask` on the `CONSOLE_READCONSOLE_CONTROL` structure and pas it into `pinputControl` as it calls `ReadConsole`, will result in the read will not necessarily waiting for a newline, but returning on a specified character as well. 

___
This is a edit/reconstruction of the content in the linked issue, the examples might need to be finetuned and potentially add links to some of the variables mentioned.

**Comment by zadjii-msft** [comment]
That looks good enough to me. Heck, I barely understand what that code is doing, but the description looks good enough to me.
