### ISSUE TITLE
GetConsoleOriginalTitle is documented incorrectly

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/Console-Docs#228]
Ported from MSFT:5123924

Read the documentation at https://msdn.microsoft.com/en-us/library/windows/desktop/ms683168(v=vs.85).aspx

Expected: the correct behavior should be documented.

Actual:

If the function succeeds, the return value is the length of the string copied to the buffer, in characters.

If the buffer is not large enough to store the title, the return value is zero and GetLastError returns ERROR_SUCCESS.

If the function fails, the return value is zero and GetLastError returns the error code.

This is not correct. A correct description of the return value, as of Windows 8.1, is:

If nSize is 0, the return value is 0.

Otherwise:

If the function succeeds, the return value is the length of the original console title, in characters.

If the function fails, the return value is zero and GetLastError returns the error code.

**Comment by pizzaz93** [comment]
```
If *nSize* is zero, the return value is zero.

If the function succeeds, the return value is the length of the original console title, in characters.

If the function fails, the return value is zero and [**GetLastError**](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns the error code.
```

**Comment by zadjii-msft** [comment]
Looks right to me 👍
