### ISSUE TITLE
Documentation for FreeConsole API is wrong (for case when console is already attached)

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/Console-Docs#229]
Ported from MSFT:9194124

The documentation says:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms683150(v=vs.85).aspx

A process can be attached to at most one console. If the calling process is not already attached to a console, the error code returned is ERROR_INVALID_PARAMETER (87).

But the code actually says and does:

    //
    // We succeed the free console request even if there's nothing to be freed
    // to maintain compatibility with previous releases.
    //

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b013865-fcaf-8009-6c6f-cf358d98914e
* Version Independent ID: 33211ae1-fe61-845c-040c-b92ea8b0e25f
* Content: [FreeConsole function - Windows Console](https://docs.microsoft.com/en-us/windows/console/freeconsole?redirectedfrom=MSDN)
* Content Source: [docs/freeconsole.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/freeconsole.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by pizzaz93** [comment]
`A process can be attached to at most one console.`
/* Second paragraph content */
 `If the calling process is not already attached to a console, the **FreeConsole** request still succeeds.`

**Comment by zadjii-msft** [comment]
LGTM 👍
