### ISSUE TITLE
DISABLE_NEWLINE_AUTO_RETURN doc says something about waiting for next char, that's incorrect

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/Console-Docs#230]
Ported from MSFT:9557746
https://github.com/Microsoft/BashOnWindows/issues/1273#issuecomment-256745667

 

n https://msdn.microsoft.com/en-us/library/windows/desktop/ms683167(v=vs.85).aspx search for:

In contrast with this flag set, the scroll operation and cursor move is delayed until the next character arrives.

 

This really shouldn't talk about the delayed state. It doesn't delay it. It just doesn't do the newline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c070233-07ad-227e-dd06-aacfbf24e446
* Version Independent ID: 9eb8954f-69fc-9758-e051-56bf9a85fb31
* Content: [GetConsoleMode function - Windows Console](https://docs.microsoft.com/en-us/windows/console/getconsolemode?redirectedfrom=MSDN)
* Content Source: [docs/getconsolemode.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/getconsolemode.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by pizzaz93** [comment]
`In contrast with this flag set, the scroll operation and cursor move do not move to another line.` ?

**Comment by zadjii-msft** [comment]
I'd maybe just alter that a little for more clarity on the order of operations here:

```diff
-In contrast with this flag set, the scroll operation and cursor move do not move to another line.
+In contrast with this flag set, the cursor does not move to the next line, and the scroll operation is not performed.
```
