### ISSUE TITLE
virtual terminal input should be read, not write?

### ISSUE THREAD

**Issue by kerravon86** [MicrosoftDocs/Console-Docs#235]
Did you mean ReadFile and ReadConsole here?

ENABLE_VIRTUAL_TERMINAL_INPUT 0x0200 | Setting this flag directs the Virtual Terminal processing engine to convert user input received by the console window into Console Virtual Terminal Sequences that can be retrieved by a supporting application through WriteFile or WriteConsole functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ea4fba-5919-fff6-9941-f213a557c651
* Version Independent ID: 5c22080b-6969-4721-5e5c-40c348680701
* Content: [SetConsoleMode function - Windows Console](https://docs.microsoft.com/en-us/windows/console/setconsolemode)
* Content Source: [docs/setconsolemode.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/setconsolemode.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Whoa. Yes I did. Thanks!
