### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by saha80** [MicrosoftDocs/Console-Docs#237]
Invalid link `[Windows Terminal](/terminal/get-started)` expands as:
`https://github.com/MicrosoftDocs/Console-Docs/blob/main/terminal/get-started`
https://github.com/MicrosoftDocs/Console-Docs/blob/c2bbd402eacd4f29c613b42fcf82b72573e982b7/docs/ecosystem-roadmap.md?plain=1#L21

**Comment by pizzaz93** [comment]
Would the proper link be https://github.com/microsoft/terminal?

**Comment by zadjii-msft** [comment]
I think the right link should be to https://docs.microsoft.com/en-us/windows/terminal/, but I don't know how to correctly link across docs repos like that 😬
