### ISSUE TITLE
No instructions about changing font without Console API

### ISSUE THREAD

**Issue by dannycoh** [MicrosoftDocs/Console-Docs#246]
[Enter feedback here]
The first sentence is "Virtual terminal sequences are control character sequences that can control cursor movement, color/font mode".
As I read it I understand that I can set a console font using VTS.
However, there are no other instructions or escape codes to do this.
I googled many different phrases and found not even a single example of using VTS code to set the console font.
If it is a mistake, please delete it.
If there is a way to set the font using VTS, please provide the instructions/example.
Currently, it seems the only way to set the console font is to resort to the old Console WinAPI...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/main/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by pizzaz93** [comment]
This refers to the first sentence on https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences.

It could be edited to `Virtual terminal sequences are control character sequences that can control cursor movement, console color, and other operations when written to the output stream.`
