### ISSUE TITLE
The result should be 16 but it says 610, where am I doing wrong?

### ISSUE THREAD

**Issue by Huseyinkaymaz** [MicrosoftDocs/Console-Docs#255]
![image](https://user-images.githubusercontent.com/100446595/163697488-dcb4312e-8677-408e-bf1b-47aa4259bb19.png)
The result should be 16 but it says 610, where am I doing wrong?

**Comment by Huseyinkaymaz** [comment]
```
            int a, b;
            Console.WriteLine("A sayisini giriniz");
            a = Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("B sayisini giriniz");
            b = Convert.ToInt32(Console.ReadLine());

            int toplam = 0;
            for (int i = a; i <= b; i++)
            {
                if (i % 2 == 0)
                {
                    toplam += i;
                }
            }

            Console.WriteLine("Arasındaki çift sayiların toplamı= "+ toplam + 10);
```

**Comment by Huseyinkaymaz** [comment]
True :
Console.WriteLine("Arasındaki çift sayiların toplamı= "+ (toplam +10) );

**Comment by zadjii-msft** [comment]
Yea this is more a question for the C# `System.Console` docs, wherever they might be located. Somewhere more like: https://docs.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings

I'm betting in C# that `operator+` for a `string` and an `int` will first convert the int to a string, then append it to the first string.
