### ISSUE TITLE
Documented ASCII Escape Sequence for setting the alternate/main screen buffer shows spaces in the 1049 string

### ISSUE THREAD

**Issue by RonWright** [MicrosoftDocs/Console-Docs#264]
The AES for setting the alternate screen buffer is documented as:  ESC [ ? 1 0 4 9 h
Likewise the AES for setting the main screen buffer is documented as:  ESC [ ? 1 0 4 9 l

The doc has spaces in the "1 0 4 9" portion and should not contain spaces as in "1049".
The extra spaces prevent a search for "1049".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#screen-colors)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/main/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by pizzaz93** [comment]
The same feedback would be valid for this section as well.

![Screenshot 2022-05-16 9 59 22 AM](https://user-images.githubusercontent.com/10904763/168645131-9221ac2b-a02e-4838-b396-c206472deaf9.png)

**Comment by zadjii-msft** [comment]
This is pretty consistent across the entire document. Each character is separated by spaces. Because `esc` isn't otherwise printable, it's represented as the single string `ESC`. 

This is consistent with the definitive escape code documentation: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
