### ISSUE TITLE
When to use GetLastError

### ISSUE THREAD

**Issue by dannycoh** [MicrosoftDocs/Console-Docs#265]
[Enter feedback here]
After reading these sentences I am confused:

> If the function fails, the return value is INVALID_HANDLE_VALUE. To get extended error information, call [GetLastError](https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror).

> If an application does not have associated standard handles, such as a service running on an interactive desktop, and has not redirected them, the return value is NULL.

It seems my code should check the return code for INVALID_HANDLE_VALUE and then to NULL. As I understand it, every other return value is a valid handle. So when should I call GetLastError?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180ec66b-7926-88e2-4315-673a2759f800
* Version Independent ID: 5f648f55-41cb-3cf4-d671-9f07a9aeea48
* Content: [GetStdHandle function - Windows Console](https://docs.microsoft.com/en-us/windows/console/getstdhandle)
* Content Source: [docs/getstdhandle.md](https://github.com/Microsoft/Console-Docs/blob/main/docs/getstdhandle.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by dannycoh** [comment]
Anyone???

**Comment by DHowett** [comment]
Hey @dannycoh, sorry about the radio silence here! I need to make sure we include this docs repo in our triage process.

You should call `GetLastError` when the return is `INVALID_HANDLE_VALUE`.

`NULL` is a valid **non-error return value**, and `GetLastError` will not report an error.
