### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by theking2** [MicrosoftDocs/Console-Docs#287]
Terminal appears in the wrong language.

In a default Dutch language Terminal appears in German. German is not Dutch. 

However as I'm in Switzerland it might be that Terminal is using the wrong language settings.

I know internationalisation is difficult. But if you cannot solve this at least let the user select the language.

**Comment by theking2** [comment]
https://stackoverflow.com/a/27642206/718960

**Comment by zadjii-msft** [comment]
I don't think the Terminal is translated into Dutch. We're tracking additional languages in https://github.com/microsoft/terminal/issues/10667. Thanks!
