### ISSUE TITLE
No documentation on how to create my own Console emulator.

### ISSUE THREAD

**Issue by a-usr** [MicrosoftDocs/Console-Docs#303]
As the title suggests, i couldnt find any pointers to how i would create my own terminal emulator / console host. In my opinion, even if it isnt on here, it should be at least somewhere else in the documentation.

**Comment by a-usr** [comment]
Thank you for you guidance. I will look into the terminal repository and the reimplementation you referenced. If its ok, I would like to come back to this issue if i face any problems that i am unable to solve alone?

**Comment by lhecker** [comment]
Sure! Although it might almost be more fitting to start a discussion in the terminal repository: https://github.com/microsoft/terminal/discussions

**Comment by a-usr** [comment]
I feel so stupid right now.. i was looking for the best place to ask this, and i first even wanted to open a issue in the terminal repository... however i completely forgot about github discussions.. thank you for reminding me!
