### ISSUE TITLE
Error: 0x800f080c Feature name Microsoft-Windows-Subsystem-Linux is unknown

### ISSUE THREAD

**Issue by stomas8** [MicrosoftDocs/Console-Docs#310]
get error:
Error: 0x800f080c Feature name Microsoft-Windows-Subsystem-Linux is unknown...

here is my system information

	Host Name:                 DESKTOP-NQTTP57
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Steven P. Tomas
Registered Organization:
Product ID:                00330-80000-00000-AA849
Original Install Date:     2/6/2024, 10:24:37 AM
System Boot Time:          2/5/2024, 11:24:24 PM
System Manufacturer:       TOSHIBA
System Model:              Qosmio X70-A
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~800 Mhz
BIOS Version:              Insyde Corp. 1.30, 9/18/2013
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     24,500 MB
Available Physical Memory: 16,832 MB
Virtual Memory: Max Size:  42,860 MB
Virtual Memory: Available: 31,801 MB
Virtual Memory: In Use:    11,059 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-NQTTP57
Hotfix(s):                 N/A
Network Card(s):           3 NIC(s) Installed.
                           [01]: Qualcomm Atheros AR8161 PCI-E Gigabit Ethernet Controller (NDIS 6.30)
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wireless-N 7260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.179.171
                                 IP address(es)
                                 [01]: 192.168.179.38
                                 [02]: fe80::49f6:cfe6:58b2:be5
                                 [03]: 2607:fb90:fd8f:4b83:3873:232:947c:cc36
                                 [04]: 2607:fb90:fd8f:4b83:49f6:cfe6:58b2:be5
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

how to resolve this issue

**Comment by lhecker** [comment]
Hey! Unfortunately, that's not an issue that's related to Windows Terminal. Maybe someone else on the internet had your problem as well and solved it? I found this via Google: https://superuser.com/questions/1742960/error-0x800f080c-trying-to-install-wsl
I hope you can resolve this problem soon!

**Comment by stomas8** [comment]
thank you
