### ISSUE TITLE
GetConsoleProcessList doesn't work with zero arguments

### ISSUE THREAD

**Issue by KubaO** [MicrosoftDocs/Console-Docs#32]
From a comment by popchoc:

> `lpdwProcessList` and `dwProcessCount` cannot be 0 or the function will return 0 and set error `ERROR_INVALID_PARAMETER`. If you are trying to obtain the process count you must pass an array that contains at least one element.

This should be made explicit.

**Comment by miniksa** [comment]
Let me investigate this and see if this isn't a bug.
I filed MSFT: 19193481 internally to track the work. Will update when I get around to it.

**Comment by miniksa** [comment]
OK, it's been this way forever. In lieu of changing behavior and breaking compatibility, I'll update the doc.

**Comment by miniksa** [comment]
Complete.
