### ISSUE TITLE
Please include a working sample for PseudoConsole

### ISSUE THREAD

**Issue by asmichi** [MicrosoftDocs/Console-Docs#66]
Please include a working sample; the sample code in the doc does not even compile:

- Undefined function `UpdateProcThreadAttributeList`; the correct identifier will be `UpdateProcThreadAttribute`.
- Missing definition of `hPC`.
- Missing semicolon at `return HRESULT_FROM_WIN32(GetLastError())` below `if (!CreatePipe(&outputReadSide, &outputWriteSide, NULL, 0))`

I found Microsoft samples in https://github.com/Microsoft/console. A link to the project would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ed724a-32d9-72fc-a938-e181e3fde0e8
* Version Independent ID: d6706818-fb3d-7400-a549-9d3a77602f33
* Content: [Creating a Pseudoconsole session - Windows Console](https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session)
* Content Source: [docs/creating-a-pseudoconsole-session.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/creating-a-pseudoconsole-session.md)
* Product: **console**
* GitHub Login: @miniksa
* Microsoft Alias: **miniksa**

**Comment by miniksa** [comment]
Complete.

**Comment by asmichi** [comment]
Great. Thank you!!
