### ISSUE TITLE
GetConsoleScreenBufferInfoEx fn documentation is incorrect !

### ISSUE THREAD

**Issue by Victor-Soldatov** [MicrosoftDocs/Console-Docs#67]
Fn is failed in case of lpConsoleScreenBufferInfoEx -&gt;cbSize member is being not initialized with sizeof(CONSOLE_SCREEN_BUFFER_INFOEX)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315a09dd-2cfc-0927-b2ff-e5b425357d88
* Version Independent ID: bb8b73c9-24c2-750a-ff2c-e1216170dc91
* Content: [GetConsoleScreenBufferInfoEx function - Windows Console](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfoex)
* Content Source: [docs/getconsolescreenbufferinfoex.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/getconsolescreenbufferinfoex.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by bitcrazed** [comment]
All Win32 functions that accept a pointer to a struct expect the struct to exist and for its size field (cbSize) to be initialized. If not, the call will fail.
