### ISSUE TITLE
Forced Shutdown

### ISSUE THREAD

**Issue by aybassiouny** [MicrosoftDocs/Console-Docs#73]
According to [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/441a00b6-5d96-42f5-8596-47ed43c10868/setconsolectrlhandler-routine-exits-after-5-seconds-from-close-process) and [this](https://stackoverflow.com/questions/47041407/why-does-my-windows-console-close-event-handler-time-out) there's a forced shutdown mechanism that windows follows for apps that refuse to shutdown. Is this still the case? In case this is a deprecated behavior, should a note about this in Remarks be left? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ba5094-8462-1c39-3894-2b9329e42d0d
* Version Independent ID: 3286f315-ed8b-f718-55c0-b82d8bd96aca
* Content: [HandlerRoutine callback function - Windows Console](https://docs.microsoft.com/en-us/windows/console/handlerroutine)
* Content Source: [docs/handlerroutine.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/handlerroutine.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by bitcrazed** [comment]
Apps that hang when terminating may be forcibly terminated by the OS. If your app needs to save state/data/etc. during shutdown, I'd recommend performing the save operation **before** terminating the app.

**Comment by aybassiouny** [comment]
How long does the kernel wait before these apps are forcibly shutdown? 

Suucest to add that info to documentation too.

**Comment by miniksa** [comment]
Note to self: I spent some time trying to trace through how this works and what the timeout is, and I was unsuccessful.

**Comment by miniksa** [comment]
@DHowett-MSFT, didn't you just figure this out yesterday for a completely unrelated reason? Can you detail here and/or update the doc directly?

**Comment by DHowett-MSFT** [comment]
Hey, good callback! Here's what I've got:

## Timeouts

| Event                  | Circumstances                   | Timeout                                                     |
|------------------------|---------------------------------|-------------------------------------------------------------|
| `CTRL_CLOSE_EVENT`     | _any_                           | system parameter `SPI_GETHUNGAPPTIMEOUT`, 5000ms            |
| `CTRL_LOGOFF_EVENT`    | _quick_[1] | registry key `CriticalAppShutdownTimeout` or 500ms          |
| `CTRL_LOGOFF_EVENT`    | _none of the above_             | system parameter `SPI_GETWAITTOKILLTIMEOUT`, 5000ms         |
| `CTRL_SHUTDOWN_EVENT`  | **service process**             | system parameter `SPI_GETWAITTOKILLSERVICETIMEOUT`, 20000ms |
| `CTRL_SHUTDOWN_EVENT`  | _quick_[1] | registry key `CriticalAppShutdownTimeout` or 500ms          |
| `CTRL_SHUTDOWN_EVENT`  | _none of the above_             | system parameter `SPI_GETWAITTOKILLTIMEOUT`, 5000ms         |
| `CTRL_C`, `CTRL_BREAK` | _any_                           | **no timeout**                                              |

_[1]: "quick" events are never used, but there's still code to support them._

**Comment by miniksa** [comment]
WELP. I will merge that table into the page then.
