### ISSUE TITLE
Type in Cursor Visibility table

### ISSUE THREAD

**Issue by elviswolcott** [MicrosoftDocs/Console-Docs#74]
In the cursor visibility section, the row for `ESC [ ? 12 l`	the Description `Text Cursor Enable Blinking`	 does not match the behavior `Stop blinking the cursor`. This would appear to be a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc536527-f75d-5a03-7b5a-338a08e40d2f
* Version Independent ID: 097f43d9-243f-466e-1f99-6cfa1f4bfb1f
* Content: [Console Virtual Terminal Sequences - Windows Console](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)
* Content Source: [docs/console-virtual-terminal-sequences.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/console-virtual-terminal-sequences.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Oop, yes. You are right. Fixing.
