### ISSUE TITLE
Bug in CTRL_BREAK_EVENT

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/Console-Docs#76]
The text says it passes the signal on, but the code does return TRUE instead of return FALSE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6978c5ff-60e8-16e2-f21a-f373e912133c
* Version Independent ID: f98a99d1-db40-4fd5-ed0b-8f11ec9f49ba
* Content: [Registering a Control Handler Function - Windows Console](https://docs.microsoft.com/en-us/windows/console/registering-a-control-handler-function)
* Content Source: [docs/registering-a-control-handler-function.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/registering-a-control-handler-function.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Yep, you're right. I'm fixing it up.
