### ISSUE TITLE
Wrong TOC location

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/Console-Docs#79]
This page doesn't appears in the TOC on the left under Console API Functions, but all the other entries are actual functions, not descriptions of groups of functions. This page should probably be included under Using The Console API instead of Console API Functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 451d7ad5-29c2-2038-88c2-686a54540770
* Version Independent ID: 517277b3-33c5-a4c3-044b-c5cde06fa8d6
* Content: [High-Level Console Input and Output Functions - Windows Console](https://docs.microsoft.com/en-us/windows/console/high-level-console-input-and-output-functions)
* Content Source: [docs/high-level-console-input-and-output-functions.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/high-level-console-input-and-output-functions.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Yep, that makes way more sense to me. I moved it. Thanks!
