### ISSUE TITLE
Extra lines after first table

### ISSUE THREAD

**Issue by davidmatson** [MicrosoftDocs/Console-Docs#80]
There are extra horizontal lines after the first table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a7a9b2-1db0-039d-5daa-adac41888597
* Version Independent ID: 4262275f-c78f-5ac2-7633-80655b2fe76c
* Content: [Low-Level Console Output Functions - Windows Console](https://docs.microsoft.com/en-us/windows/console/low-level-console-output-functions)
* Content Source: [docs/low-level-console-output-functions.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/low-level-console-output-functions.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Yes, there are. Thanks!
