### ISSUE TITLE
Unclear parameter description

### ISSUE THREAD

**Issue by darjeeling-uk** [MicrosoftDocs/Console-Docs#81]
&gt; dwProcessCount [in]
&gt; The maximum number of process identifiers that can be stored in the lpdwProcessList buffer. 
&gt; The maximum number of process identifiers that can be stored in the lpdwProcessList buffer. This must be greater than 0 and refer to the length of lpdwProcessList.

"This must be greater than 0" is fine.  "..and refer to the length of lpdwProcessList" is at best misleading.  The length of lpdwProcessList is 4 or 8 (i.e. the size of a pointer in 32- or 64-bit platform).  And how exactly does dwProcessCount "refer" to that length?  And do you really mean to say "length" - that's just asking for confusion between byte-length and count of entries that used to be a problem in so many API docs.
Suggestion - just end the sentence after "must be greater than 0".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4a3183-8e9b-d212-7754-1db40890c7ad
* Version Independent ID: 74da3ad0-14a6-838f-e2e1-e01111e19b38
* Content: [GetConsoleProcessList function - Windows Console](https://docs.microsoft.com/en-us/windows/console/getconsoleprocesslist)
* Content Source: [docs/getconsoleprocesslist.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/getconsoleprocesslist.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Sorry, I meant length in count of entries. I'll get around to updating it, or you're welcome to submit the pull.

**Comment by bitcrazed** [comment]
Welcome to collaborative docs 😊

Better still – if you sign-in and hit the Edit button, you’ll be able to edit the page and submit your proposed changes, which should handle all the fork & branch creation for you!

Rich.

**Comment by miniksa** [comment]
Looks like this is resolved. Closing.
