### ISSUE TITLE
Return value is backwards in documentation

### ISSUE THREAD

**Issue by aandsc** [MicrosoftDocs/Console-Docs#84]
Instead of "character cell rows (X member) and columns (Y member)" it should read "character cell columns (X member) and rows (Y member)".  This is consistent with the COORD structure definition and also verified by return values from the call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3038abb3-34d1-c415-307f-cff9a7353b1c
* Version Independent ID: 250aa976-4b1e-3d2a-577d-0bb0862ad9c1
* Content: [GetLargestConsoleWindowSize function - Windows Console](https://docs.microsoft.com/en-us/windows/console/getlargestconsolewindowsize)
* Content Source: [docs/getlargestconsolewindowsize.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/getlargestconsolewindowsize.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
Yep, thanks!
