### ISSUE TITLE
Unclear expected behavior

### ISSUE THREAD

**Issue by ConEmu** [MicrosoftDocs/Console-Docs#86]
From the description it's unclear what size would new buffer have. Should it have the same dimensions, or it's created with some undefined defaults?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e498c98b-1f3f-f1dc-e302-d26eee2a07ac
* Version Independent ID: f2a6526d-06ea-8630-5099-998be867f602
* Content: [CreateConsoleScreenBuffer function - Windows Console](https://docs.microsoft.com/en-us/windows/console/createconsolescreenbuffer#feedback)
* Content Source: [docs/createconsolescreenbuffer.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/createconsolescreenbuffer.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
It copies many of the properties of the active output buffer at the time of creation. I'll document this.
