### ISSUE TITLE
Why can't SetStdHandle redirect the process's stdanard input/output?

### ISSUE THREAD

**Issue by yh-git** [MicrosoftDocs/Console-Docs#95]
I've tried many times to use this funtion to redirect printf and other stdanard input/output function,but finally found SetStdHandle can't do this.
The name of this function is really confusing, and I suggest to explain what this function exactly do, and what should do to redirect stdanard input/output in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9ed640-1bd3-bca5-8f65-1677fd7ae728
* Version Independent ID: a1c51580-ce41-6809-dcce-8339f000eac3
* Content: [SetStdHandle function - Windows Console](https://docs.microsoft.com/en-us/windows/console/setstdhandle)
* Content Source: [docs/setstdhandle.md](https://github.com/Microsoft/Console-Docs/blob/master/docs/setstdhandle.md)
* Product: **console**
* GitHub Login: @bitcrazed
* Microsoft Alias: **richturn**

**Comment by miniksa** [comment]
`printf` is a CRT function, not a Win32 function.

`SetStdHandle` inside a process will affect the Windows handles `STD_INPUT_HANDLE` and `STD_OUTPUT_HANDLE` as provided by the Win32 API.

`printf` is not affected as it operates on things like the CRT handle `stdout` from the CRT API.

If you want to modify the behavior of CRT functions, you need to use one of the CRT functions that can manipulate the CRT handles like `freopen_s`.

As an example I've done `freopen_s(&std_out, "CONOUT$", "w+", stdout);` to reassign the CRT handles to the current console session after changing it with `FreeConsole` and `AttachConsole` to a different PID. You can my example here: https://github.com/microsoft/terminal/blob/master/src/host/ft_host/InitTests.cpp#L214

If this does indeed accomplish what you're looking for, let me know and I will update the documentation.

**Comment by yh-git** [comment]
Sorry, I don't quite understand.
I once wrote a program successfully redirect std input/output of a child process by specifying hStdInput/hStdOutput in STARTUPINFO (It can redirect both CRT fuction like printf and Win32 function like WriteFile to hStdout).
but this time I want to redirect the process itself instead of a child process....
I thought all CRT functions finally finish their work by calling Win32 funtion,  so maybe there is a simple way to redirect both Win32 and CRT Input/Output functions.

Thank u very much!!!!

**Comment by miniksa** [comment]
The CRT functions do accomplish their work by calling Win32 functions, but they open all their handles before your program reaches its `main` or `wmain` function. So if you modify the Win32 handles after it starts, the CRT ones will not automatically update and you will have to do it yourself (or use Win32 APIs to access the streams instead.)

This works with `STARTUPINFO` on process creation because you're replacing the handles into the new process *before* it starts and before the CRT sets itself up prior to the `main` or `wmain` being called in the new process.

**Comment by yh-git** [comment]
> The CRT functions do accomplish their work by calling Win32 functions, but they open all their handles before your program reaches its `main` or `wmain` function. So if you modify the Win32 handles after it starts, the CRT ones will not automatically update and you will have to do it yourself (or use Win32 APIs to access the streams instead.)
> 
> This works with `STARTUPINFO` on process creation because you're replacing the handles into the new process _before_ it starts and before the CRT sets itself up prior to the `main` or `wmain` being called in the new process.

Thanks alot! now I understant why i failed. and maybe you can improve the document by explaining this!
